[package]
name = "castle_input_cursor"
version = "0.20.1"
edition = "2021"
license = "MIT"
description = "Castle Input Cursor"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
