pub mod tests_self_validation;
pub mod tests_validate_backend_to_schema;
pub mod tests_validate_schema_to_query;
pub mod tests_castle_and_resolving_wants;
pub mod tests_individual_resolvers_with_schema_and_query;