[package]
name = "castle_query_parser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
castle_error = { path = "../castle_error", version = "0.2.0" }
castle_tokenizer = { path = "../castle_tokenizer", version = "0.2.0" }
castle_shared_parser = { path = "../castle_shared_parser", version = "0.2.0" }
